<x-layout.standar-nasional-pendidikan-tinggi>
    
    <ul class="flex flex-col gap-3 text-sm w-50 min-w-50 p-3 border rounded-md border-gray-200 bg-gray-100">
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.peringkat-akreditasi') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.peringkat-akreditasi') }}">Peringkat Akreditasi</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.jumlah-lulusan') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.jumlah-lulusan') }}">Jumlah Lulusan</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.jumlah-mahasiswa-lulus-tepat-waktu') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.jumlah-mahasiswa-lulus-tepat-waktu') }}">Jumlah Mahasiswa Lulus Tepat Waktu</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.jumlah-mahasiswa-putus-studi') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.jumlah-mahasiswa-putus-studi') }}">Jumlah Mahasiswa Putus Studi</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.presentase-mahasiswa-lulus-dengan-ipk-3') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.presentase-mahasiswa-lulus-dengan-ipk-3') }}">Presentase Mahasiswa Lulus dengan IPK > 3.0</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.program-doktor') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.program-doktor') }}">Program Doktor</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.program-magister') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.program-magister') }}">Program Magister</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.presentase-mahasiswa-lulus-dengan-ipk-2') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.presentase-mahasiswa-lulus-dengan-ipk-2') }}">Presentase Mahasiswa Lulus dengan IPK > 2.0</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.program-sarjana-sarjana-terapan') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.program-sarjana-sarjana-terapan') }}">Program Sarjana / Sarjana Terapan</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.program-diploma') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.program-diploma') }}">Program Diploma Tiga / Diploma Dua / Diploma Satu</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.program-profesi') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.program-profesi') }}">Program Profesi</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.proses-pembelajaran') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.proses-pembelajaran') }}">Proses Pembelajaran</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.penilaian-pembelajaran') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.penilaian-pembelajaran') }}">Penilaian Pembelajaran</a></li>
        <li><a class="flex w-full px-2 py-1 rounded-sm {{ request()->routeIs('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.jumlah-dosen') ? 'bg-linear-to-r from-zinc-400 to-gray-400 text-zinc-50 ' : '' }}" href="{{ route_f('dashboard.penetapan-pelaksanaan.standar-nasional-pendidikan-tinggi.program-studi.jumlah-dosen') }}">Jumlah Dosen</a></li>
    </ul>
    
    <div class="w-full text-sm">
        {{ $slot }}
    </div>
    
</x-layout.standar-nasional-pendidikan-tinggi>